<?php

return array (
  'version' => '6.4.14',
  'list_screen' => 
  array (
    'title' => '',
    'type' => 'mp-solution',
    'id' => '6793eef3ee78d',
    'updated' => 1737748372,
    'columns' => 
    array (
      '2b9716dccdd2f2' => 
      array (
        'type' => 'column-featured_image',
        'label' => 'Featured Image',
        'width' => '',
        'width_unit' => '%',
        'featured_image_display' => 'image',
        'image_size' => 'cpac-custom',
        'image_size_w' => '60',
        'image_size_h' => '60',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '2b9716dccdd2f2',
      ),
      'title' => 
      array (
        'type' => 'title',
        'label' => 'Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'title',
      ),
      '2c93cd1fcf1aa0' => 
      array (
        'type' => 'field_6792fc34efd01',
        'label' => 'Contributor',
        'width' => '',
        'width_unit' => '%',
        'term_property' => '',
        'term_link_to' => 'filter',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '2c93cd1fcf1aa0',
      ),
      '436c1dd8ad9168' => 
      array (
        'type' => 'field_6792ade8dc767',
        'label' => 'Category',
        'width' => '',
        'width_unit' => '%',
        'term_property' => '',
        'term_link_to' => 'filter',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '436c1dd8ad9168',
      ),
      '40080236126e98' => 
      array (
        'type' => 'field_6792adbfdc766',
        'label' => 'Solution Type',
        'width' => '',
        'width_unit' => '%',
        'term_property' => '',
        'term_link_to' => 'filter',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => '40080236126e98',
      ),
      'wpseo-score' => 
      array (
        'type' => 'wpseo-score',
        'label' => '<span class="yoast-column-seo-score yoast-column-header-has-tooltip" data-tooltip-text="SEO score"><span class="screen-reader-text">SEO score</span></span></span>',
        'width' => '63',
        'width_unit' => 'px',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score',
      ),
      'wpseo-score-readability' => 
      array (
        'type' => 'wpseo-score-readability',
        'label' => '<span class="yoast-column-readability yoast-column-header-has-tooltip" data-tooltip-text="Readability score"><span class="screen-reader-text">Readability score</span></span></span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-score-readability',
      ),
      'wpseo-title' => 
      array (
        'type' => 'wpseo-title',
        'label' => 'SEO Title',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-title',
      ),
      'wpseo-metadesc' => 
      array (
        'type' => 'wpseo-metadesc',
        'label' => 'Meta Desc.',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-metadesc',
      ),
      'wpseo-focuskw' => 
      array (
        'type' => 'wpseo-focuskw',
        'label' => 'Keyphrase',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'edit' => 'on',
        'bulk_edit' => 'on',
        'search' => 'on',
        'filter' => 'off',
        'filter_label' => '',
        'name' => 'wpseo-focuskw',
      ),
      'wpseo-links' => 
      array (
        'type' => 'wpseo-links',
        'label' => '<span class="yoast-linked-to yoast-column-header-has-tooltip" data-tooltip-text="Number of outgoing internal links in this post. See "Yoast Columns" text in the help tab for more info."><span class="screen-reader-text">Outgoing internal links</span></span>',
        'width' => '',
        'width_unit' => '%',
        'sort' => 'on',
        'name' => 'wpseo-links',
      ),
      'wpseo-cornerstone' => 
      array (
        'type' => 'wpseo-cornerstone',
        'label' => '<span class="yoast-column-cornerstone yoast-column-header-has-tooltip" data-tooltip-text="Is this cornerstone content?"><span class="screen-reader-text">Cornerstone content</span></span>',
        'width' => '',
        'width_unit' => '%',
        'export' => 'on',
        'sort' => 'on',
        'name' => 'wpseo-cornerstone',
      ),
    ),
    'settings' => 
    array (
      'roles' => 
      array (
      ),
      'users' => 
      array (
      ),
      'sorting' => '0',
      'sorting_order' => 'asc',
      'hide_inline_edit' => 'off',
      'hide_bulk_edit' => 'off',
      'hide_bulk_delete' => 'off',
      'hide_smart_filters' => 'off',
      'hide_segments' => 'off',
      'hide_export' => 'off',
      'hide_conditional_formatting' => 'off',
      'hide_new_inline' => 'on',
      'resize_columns' => 'off',
      'column_order' => 'off',
      'hide_filters' => 'off',
      'hide_filter_post_date' => 'off',
      'hide_filter_yoast_seo_scores' => 'off',
      'hide_filter_yoast_readability_score' => 'off',
      'hide_submenu' => 'off',
      'hide_search' => 'off',
      'hide_bulk_actions' => 'off',
      'hide_row_actions' => 'off',
      'horizontal_scrolling' => 'off',
      'primary_column' => '',
      'filter_segment' => '',
      'wrapping' => 'wrap',
    ),
  ),
);